var Name = prompt("what is your first name")
var Last = prompt("what is your last name")
var Age = prompt("what is your age")
console.log("I know you name is " + Name + " " + Last)
console.log("I Know alot about you... I know your age it " + Age)